### ISSUE TITLE
依赖 puppeteer 吗？

### ISSUE THREAD

**Issue by wind13** [valleykid/puppeteer-cn#4]
我在测试目录中运行

```
yarn add puppeteer-cn
```

顺利安装完成，但执行一个测试脚本时却得到下面的报错：

```
Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/demo/test/node_modules/puppeteer-cn/lib/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

如果依赖 `puppeteer` 的话，那还有啥意义呢？还是要安装 `puppeteer` 啊？

**Comment by valleykid** [comment]
不好意思，回答晚了~
该模块依赖 `puppeteer`，但不需要自己安装，脚本会自动检测并安装。意义请参考 [README.md](https://github.com/valleykid/puppeteer-cn/blob/master/README.md)。
我本地没有复现你的这个问题，请详细描述下你的系统、node版本和复现步骤 好吧？
