### ISSUE TITLE
更新node为V10.9.0后出错

### ISSUE THREAD

**Issue by scscms** [valleykid/puppeteer-cn#5]
因项目升级，更新node为v10.9.0就报错了

> (node:7328) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_launcher' of undefined
    at launch (D:\web\scscms\scs-monitor\node_modules\puppeteer-cn\node_modules\puppeteer\lib\Puppeteer.js:36:17)
    at utils.getChromePath.then.catch (D:\web\scscms\scs-monitor\node_modules\puppeteer-cn\lib\index.js:22:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cydiacen** [comment]
出现相同错误
node v8.9.0

**Comment by valleykid** [comment]
已修复，请重试~
